name = "spiritual-bouquet-tracker"
main = "src/main.tsx"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "npm run build"
watch_dir = "src"

[env.development]
name = "spiritual-bouquet-tracker-dev"

[env.preview]
name = "spiritual-bouquet-tracker-preview"
